const FIVE_CHARACTERS_LENGTH = "LKJHG";
const SIX_CHARACTERS_LENGTH = "LKJHGH";
const TEN_CHARACTERS_LENGTH = "LKJHG.asdf";
const FIFTY_CHARACTERS_LENGTH = "ABCDEabcde0123456789QWERTYUIOPqwertyuiopZXCVBzxcvb";

export const NO_MAX = "ANY";
export const MAX_15 = TEN_CHARACTERS_LENGTH + FIVE_CHARACTERS_LENGTH;
export const MAX_20 = TEN_CHARACTERS_LENGTH.repeat(2);
export const MAX_32 = TEN_CHARACTERS_LENGTH.repeat(3) + ".2";
export const MAX_50 = FIFTY_CHARACTERS_LENGTH;
export const MAX_80 = FIFTY_CHARACTERS_LENGTH + TEN_CHARACTERS_LENGTH.repeat(3);
export const MAX_100 = FIFTY_CHARACTERS_LENGTH.repeat(2);
export const MAX_160 = FIFTY_CHARACTERS_LENGTH.repeat(3) + TEN_CHARACTERS_LENGTH;
export const MAX_250 = FIFTY_CHARACTERS_LENGTH.repeat(5);
export const MAX_256 = FIFTY_CHARACTERS_LENGTH.repeat(5) + SIX_CHARACTERS_LENGTH;
export const MAX_260 = FIFTY_CHARACTERS_LENGTH.repeat(5) + TEN_CHARACTERS_LENGTH;
export const MAX_4000 = FIFTY_CHARACTERS_LENGTH.repeat(80);
