export const INDEX_PAGE_TITLE = "Register an overseas entity and tell us about its beneficial owners";
export const SERVICE_UNAVAILABLE = "Sorry, the service is unavailable";
export const INTERRUPT_CARD_PAGE_TITLE = "Before you start";
export const ENTITY_PAGE_TITLE = "Tell us about the overseas entity";
export const BENEFICIAL_OWNER_GOV_PAGE_HEADING = "Tell us about the government or public authority";
export const BENEFICIAL_OWNER_OTHER_PAGE_HEADING = "Tell us about the other legal entity";
export const BENEFICIAL_OWNER_STATEMENTS_PAGE_REDIRECT = "Found. Redirecting to /register-an-overseas-entity/beneficial-owner-statements";
export const BENEFICIAL_OWNER_STATEMENTS_PAGE_HEADING = "Have you identified any beneficial owners?";
export const BENEFICIAL_OWNER_TYPE_PAGE_HEADING = "Which type of beneficial owner or managing officer do you want to add?";
export const MANAGING_OFFICER_TYPE_PAGE_HEADING = "Which types of managing officers have been identified?";
export const EXPECTED_TEXT = "Page not found - Register an overseas entity and tell us about its beneficial owners";
export const INCORRECT_URL = "/register-an-overseas-entity/company-numberr";
export const MESSAGE_ERROR = "Can't connect";
export const ANY_MESSAGE_ERROR = "Any error message";
export const NO_RESOURCE_ON_PAYMENT_RESPONSE_MSG_ERROR = "No resource in payment response";
export const PAYMENT_RESPONSE_500_MSG_ERROR = "payment.service failure to create payment, http response status code=500, http errors response=[{\"error\":\"Any error message\"}].";
export const PAYMENT_RESPONSE_NO_STATUS_CODE_MSG_ERROR = "payment.service failure to create payment, http response status code=No Status Code found in response, http errors response=\"No Errors found in response\".";
export const PRESENTER_PAGE_TITLE = "Who can we contact about this application?";
export const ENTITY_PAGE_REDIRECT = "Found. Redirecting to /register-an-overseas-entity/entity";
export const BENEFICIAL_OWNER_INDIVIDUAL_PAGE_HEADING = "Tell us about the individual person";
export const MANAGING_OFFICER = "Managing officer";
export const MANAGING_OFFICER_PAGE_HEADING = "Tell us about the individual person";
export const MANAGING_OFFICER_CORPORATE_PAGE_TITLE = "Tell us about the corporate managing officer";
export const CHECK_YOUR_ANSWERS_PAGE_TITLE = "Check your answers before sending your application";
export const CONFIRMATION_PAGE_TITLE = "Application submitted";
export const UNAUTHORISED = "Unauthorised";
export const HTTP_STATUS_CODE_500 = "Http status code 500";
export const TRANSACTION_ERROR = "Transaction API request returned no response";
export const CREATE_OE__MSG_ERROR = "Something went wrong creating Overseas Entity, transactionId =";
export const FOUND_REDIRECT_TO = "Found. Redirecting to";
export const REDIRECT_TO_SIGN_IN_PAGE = "User not authenticated, redirecting to sign in page, status_code=302";
export const SERVICE_ADDRESS_SAME_AS_PRINCIPAL_ADDRESS_TEXT = "The correspondence address is the same as the entity's principal or registered office address";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_STATEMENTS_TITLE = "Have any beneficial owners been identified?";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_STATEMENTS_SUB_TEXT = "All beneficial owners have been identified and all required information can be provided";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_OTHER_SUB_TITLE = "Corporate beneficial owner";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_GOV_SUB_TITLE = "Government or public authority beneficial owner";
export const CHECK_YOUR_ANSWERS_PAGE_MANAGING_OFFICER_TITLE = "Managing officer details";
export const CHECK_YOUR_ANSWERS_PAGE_MANAGING_OFFICER_SUB_TITLE = "Individual managing officer";
export const CHECK_YOUR_ANSWERS_PAGE_MANAGING_OFFICER_CORPORATE_SUB_TITLE = "Corporate managing officer";
export const SECURE_REGISTER_FILTER_PAGE_HEADING = "Have any of the entity’s beneficial owners ever applied to protect personal information at Companies House?";
