export const SERVICE_UNAVAILABLE = "Sorry, the service is unavailable";
export const SOLD_LAND_FILTER_PAGE_TITLE = "Has the entity disposed of UK property or land since 28 February 2022?";
export const INTERRUPT_CARD_PAGE_TITLE = "Before you start";
export const ENTITY_PAGE_TITLE = "Tell us about the overseas entity";
export const WHO_IS_MAKING_FILING_PAGE_TITLE = "Who is completing this registration?";
export const OVERSEAS_ENTITY_DUE_DILIGENCE_PAGE_TITLE = "Tell us about the UK-regulated agent that carried out identity checks";
export const DUE_DILIGENCE_PAGE_TITLE = "Complete this statement to confirm that identity checks have been completed";
export const BENEFICIAL_OWNER_GOV_PAGE_HEADING = "Tell us about the government or public authority";
export const BENEFICIAL_OWNER_OTHER_PAGE_HEADING = "Tell us about the other legal entity";
export const BENEFICIAL_OWNER_STATEMENTS_PAGE_REDIRECT = "Found. Redirecting to /register-an-overseas-entity/beneficial-owner-statements";
export const BENEFICIAL_OWNER_TYPE_PAGE_REDIRECT = "Found. Redirecting to /register-an-overseas-entity/beneficial-owner-type";
export const BENEFICIAL_OWNER_STATEMENTS_PAGE_HEADING = "Have you identified any beneficial owners?";
export const BENEFICIAL_OWNER_TYPE_PAGE_HEADING = "Which type of beneficial owner or managing officer do you want to add?";
export const BENEFICIAL_OWNER_TYPE_PAGE_HEADING_ALL_IDENTIFIED_ALL_DETAILS = "Which type of beneficial owner do you want to add?";
export const BENEFICIAL_OWNER_TYPE_PAGE_HEADING_NONE_IDENTIFIED = "Which type of managing officer do you want to add?";
export const MANAGING_OFFICER_TYPE_PAGE_HEADING = "Which types of managing officers have been identified?";
export const BENEFICIAL_OWNER_TYPE_PAGE_INDIVIDUAL_BO = "Individual beneficial owner";
export const BENEFICIAL_OWNER_TYPE_PAGE_CORPORATE_BO = "Other legal entity beneficial owner";
export const BENEFICIAL_OWNER_TYPE_PAGE_GOVERNMENT_BO = "Government or public authority beneficial owner";
export const BENEFICIAL_OWNER_TYPE_PAGE_INDIVIDUAL_MO = "Individual managing officer";
export const BENEFICIAL_OWNER_TYPE_PAGE_CORPORATE_MO = "Corporate managing officer";
export const BENEFICIAL_OWNER_TYPE_LEGEND_TEXT = "Select the type of beneficial owner or managing officer you want to add";
export const BENEFICIAL_OWNER_TYPE_LEGEND_TEXT_ALL_IDENTIFIED_ALL_DETAILS = "Select the type of beneficial owner you want to add";
export const BENEFICIAL_OWNER_TYPE_LEGEND_TEXT_NONE_IDENTIFIED = "Select the type of managing officer you want to add";
export const ACCESSIBILITY_STATEMENT_PAGE_HEADING = "Accessibility statement for the 'Register an overseas entity and tell us about its beneficial owners' service";
export const EXPECTED_TEXT = "Page not found - Register an overseas entity and tell us about its beneficial owners";
export const INCORRECT_URL = "/register-an-overseas-entity/company-numberr";
export const MESSAGE_ERROR = "Can't connect";
export const ANY_MESSAGE_ERROR = "Any error message";
export const ERROR_LIST = "There is a problem";
export const NO_RESOURCE_ON_PAYMENT_RESPONSE_MSG_ERROR = "No resource in payment response";
export const PAYMENT_RESPONSE_500_MSG_ERROR = "payment.service failure to create payment, http response status code=500, http errors response=[{\"error\":\"Any error message\"}].";
export const PAYMENT_RESPONSE_NO_STATUS_CODE_MSG_ERROR = "payment.service failure to create payment, http response status code=No Status Code found in response, http errors response=\"No Errors found in response\".";
export const PRESENTER_PAGE_TITLE = "Who can we contact about this application?";
export const ENTITY_PAGE_REDIRECT = "Found. Redirecting to /register-an-overseas-entity/entity";
export const BENEFICIAL_OWNER_INDIVIDUAL_PAGE_HEADING = "Tell us about the individual person";
export const MANAGING_OFFICER = "Managing officer";
export const MANAGING_OFFICER_PAGE_HEADING = "Tell us about the individual person";
export const MANAGING_OFFICER_CORPORATE_PAGE_TITLE = "Tell us about the corporate managing officer";
export const TRUST_INFO_PAGE_TITLE = "Add trust information for the beneficial owners";
export const CHECK_YOUR_ANSWERS_PAGE_TITLE = "Check your answers before sending your application";
export const IDENTITY_CHECKS = "Identity checks";
export const CONFIRMATION_PAGE_TITLE = "Application submitted";
export const CONFIRMATION_NUMBER_OF_DAYS = "14 days";
export const CONFIRMATION_WHAT_YOU_NEED_TO_DO_NOW = "What you need to do now";
export const UNAUTHORISED = "Unauthorised";
export const HTTP_STATUS_CODE_500 = "Http status code 500";
export const TRANSACTION_ERROR = "Transaction API request returned no response";
export const CREATE_OE__MSG_ERROR = "Something went wrong creating Overseas Entity, transactionId =";
export const FOUND_REDIRECT_TO = "Found. Redirecting to";
export const REDIRECT_TO_SIGN_IN_PAGE = "User not authenticated, redirecting to sign in page, status_code=302";
export const SERVICE_ADDRESS_SAME_AS_PRINCIPAL_ADDRESS_TEXT = "The correspondence address is the same as the entity's principal or registered office address";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_STATEMENTS_TITLE = "Have any registrable beneficial owners been identified?";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_STATEMENTS_SUB_TEXT = "Some beneficial owners have been identified and all required information can be provided";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_OTHER_SUB_TITLE = "Corporate beneficial owner";
export const CHECK_YOUR_ANSWERS_PAGE_BENEFICIAL_OWNER_GOV_SUB_TITLE = "Government or public authority beneficial owner";
export const CHECK_YOUR_ANSWERS_PAGE_MANAGING_OFFICER_TITLE = "Managing officer details";
export const CHECK_YOUR_ANSWERS_PAGE_MANAGING_OFFICER_SUB_TITLE = "Individual managing officer";
export const CHECK_YOUR_ANSWERS_PAGE_MANAGING_OFFICER_CORPORATE_SUB_TITLE = "Corporate managing officer";
export const SECURE_REGISTER_FILTER_PAGE_HEADING = "Do any beneficial owners or managing officers have their personal information protected at Companies House?";
export const CANNOT_USE_SERVICE_HEADING = "You cannot use this service";
export const BENEFICIAL_OWNER_TYPE_LINK = "beneficial-owner-type";
export const CHECK_YOUR_ANSWERS_LINK = "check-your-answers";
export const TRUST_INFORMATION_LINK = "trust-information";
export const RADIO_BUTTON_YES_SELECTED = "value=\"1\" checked";
export const RADIO_BUTTON_NO_SELECTED = "value=\"0\" checked";
export const RADIO_BUTTON_AGENT_SELECTED = "value=\"agent\" checked";
export const RADIO_BUTTON_SOMEONE_ELSE_SELECTED = "value=\"someone_else\" checked";
export const INFORMATION_ON_PUBLIC_REGISTER = "All of the information provided in this section will be shown on the public Register of Overseas Entities.";
export const ALL_OTHER_INFORMATION_ON_PUBLIC_REGISTER = "All other information provided in this section will be shown on the public Register of Overseas Entities.";
export const OVERSEAS_ENTITY_DUE_DILIGENCE_NAME_TEXT = "What is their name?";
export const OVERSEAS_ENTITY_NO_EMAIL_SHOWN_INFORMATION_ON_PUBLIC_REGISTER = "The email address will not be shown";
export const DUE_DILIGENCE_NAME_TEXT = "What is the agent’s name?";
export const DUE_DILIGENCE_INFORMATION_ON_PUBLIC_REGISTER = "The email address, agent assurance code and date the identity checks were completed will not be shown.";
export const AGENT_REGISTERING = "The UK agent";
export const SOMEONE_ELSE_REGISTERING = "Someone from the overseas entity";
export const CHANGE_LINK = "Change";
export const CHANGE_LINK_NAME_PRESENTER = "Full name - who can we contact about this application";
